export const BASE_URL = "http://localhost:3001/"
export const ADD_DRIVE = "addDrive"
export const SUBMIT_AUTH = "submitAuthCode"
export const LIST_DRIVES = "listDrives"
export const GET_SCHEMA = "getSchema"
export const UPLOAD_FILE = "uploadFile"
export const LIST_FILES = "listFiles"