name: Deploy to IBM Cloud Foundry
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - name: Building react module
        run: npm run build --prefix ./ui
      - name: Copying build files to views
        run: rm -rf ./api/views || true |
          cp ./ui/build ./api/views
      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        shell: bash
      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install
        shell: bash
      - name: Authenticate with IBM Cloud CLI
        run: ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}" --no-region $( [[ ! -z "${{ secrets.RESOURCE_GROUP }}" ]] && echo "-g ${{ secrets.RESOURCE_GROUP }}")
        shell: bash
      - name: Target a Cloud Foundry org and space
        run: ibmcloud target --cf-api "${{ secrets.IBM_CLOUD_CF_API }}" -o "${{ secrets.IBM_CLOUD_CF_ORG }}" -s "${{ secrets.IBM_CLOUD_CF_SPACE }}"
        shell: bash
      - name: Deploy to Cloud Foundry
        run: pwd && ls && cd ./api && ibmcloud cf push -f manifest.yml
        shell: bash
